---
- name: 'Appending user {{ ansible_user }} to group www-data'
  user: name={{ ansible_user }} append=yes groups=www-data

- name: 'Ensure /opt/wp-cli exist'
  file: path={{ wp_cli_home }} state=directory

- name: 'Install WordPress command line tool'
  get_url: dest={{ wp_cli_home }}/wp url=https://raw.github.com/wp-cli/builds/gh-pages/phar/wp-cli.phar mode=a+x

- name: 'WordPress command line tool config file'
  template: src=wp-cli-config.yml dest={{ wp_cli_home }}/config.yml

- name: 'WordPress command line tool profile'
  copy:
    content: |
      export WP_CLI_CONFIG_PATH={{ wp_cli_home }}/config.yml
      export PATH={{ wp_cli_home }}:$PATH
    dest: /etc/profile.d/wp-cli.sh

- name: 'Copy WordPress for Odd-e data file'
  copy: src=specificationbyexampleworkshop.wordpress.xml dest={{ wp_cli_home }}

- name: 'ensure wordpress utils exist'
  template: src={{ item }} dest=/usr/bin mode=a+x
  with_items:
    - wordpress_switch_to_url
    - wordpress_switch_to_ip

- name: 'scripts for ATDD course'
  copy: src={{ item }} dest=/usr/bin mode=a+x
  with_items:
    - jinzhipinglun
    - keyipinglun
    - shanchupinglun
    - shanchuyonghu
    - shenhepinglun
    - suoyoudeyonghu
    - tianjiayonghu
    - wordpress_reset_config.sh
    - xinzengbianjiyonghu
    - xiugaimima
    - zhongxuanbu

- name: 'WordPress wwwroot directory'
  file: path="{{ wordpress_wwwroot }}" state=directory owner="{{ ansible_user }}" group=www-data mode=ug+rw,o-w

- name: 'Update system motd'
  template: src=motd dest=/etc/motd

- name: 'Copy install wordpress script'
  template: src=install_wordpress.sh.j2 dest="{{ wp_cli_home }}/install_wordpress.sh" mode=a+x

- name: 'Install WordPress using wp-cli'
  shell: |
    set -o pipefail
    "{{ wp_cli_home }}/install_wordpress.sh"
  args:
    creates: "{{ wordpress_wwwroot }}/wordpress_{{ wordpress_version }}.txt"
    executable: /bin/bash
  become: no

- name: 'remove default index.html'
  file: name={{ wordpress_wwwroot }}/index.html state=absent

- name:  'enables the Apache2 module "rewrite"'
  apache2_module: state=present name=rewrite
  notify: Restart apache2

- name: 'Allow .htaccess overwriten for default website'
  template: src=default_www_htaccess.conf.j2 dest=/etc/apache2/conf-enabled/default_www_htaccess.conf
  notify: Restart apache2

- name: '.htaccess for WordPress'
  copy: src=htaccess.txt dest={{ wordpress_wwwroot }}/.htaccess owner=www-data group=www-data mode=ug+rw,o-w
