---
- name: 'Install Apache httpd'
  apt: name=apache2

- name: 'Install MySQL server'
  apt: name={{ item }}
  with_items:
    - python-mysqldb
    - mysql-server
  register: mysql_server

- name: 'Change MySQL configuration'
  shell: sed -i.orig "/bind-address/cbind-address = 0.0.0.0" /etc/mysql/my.cnf
  when: mysql_server|changed

- name: 'Install PHP'
  apt: name=php5,php5-mysql

- name: 'MySQL DB for WordPress'
  mysql_db: name={{ wordpress_mysql_database }} encoding=utf8 collation=utf8_bin

- name: 'MySQL user for WordPress'
  mysql_user: name={{ wordpress_mysql_username }} password={{ wordpress_mysql_password }} priv=*.*:ALL state=present

- name: 'Ensure /opt/wp-cli exist'
  file: path={{ wp_cli_home }} state=directory

- name: 'Install WordPress command line tool'
  get_url: dest={{ wp_cli_home }}/wp url=https://raw.github.com/wp-cli/builds/gh-pages/phar/wp-cli.phar

- name: 'Make wp executable'
  file: path={{ wp_cli_home }}/wp mode=a+x

- name: 'WordPress command line tool config file'
  template: src=wp-cli-config.yml dest={{ wp_cli_home }}/config.yml

- name: 'WordPress command line tool profile'
  template: src=wp-cli.sh dest=/etc/profile.d/
