- name: 'Update system packages cache every a week'
  apt: update_cache=yes cache_valid_time=604800
  notify:
    - upgrade packages

- name: Enable en & zh locales
  lineinfile: path=/etc/locale.gen line="{{ item }} {{ item | regex_replace('[^.]+\.', '') }}"
  with_items: "{{ locales }}"

- name: 'Ensure locales'
  locale_gen: name="{{ item }}"
  with_items: "{{ locales }}"

- name: 'Ensure avahi'
  apt: name=avahi-daemon
