- name: 'Update system packages cache every a week'
  apt: update_cache=yes cache_valid_time=604800
  notify:
    - upgrade packages

- name: 'Locales'
  locale_gen: name="{{ item }}"
  with_items: "{{ locales }}"

- name: 'ensure avahi'
  apt: name=avahi-daemon
