- name: 'Install MySQL server'
  apt: name={{ item }}
  with_items:
    - python-mysqldb
    - mysql-server

- name: 'Allow from anywhere to connect'
  lineinfile:
    path: /etc/mysql/mariadb.conf.d/50-server.cnf
    regexp: '^\s*bind-address\s*=\s*'
    insertafter: "[mysqld]"
    line: "bind-address            = 0.0.0.0"
  notify: Restart mysql server

- name: 'MySQL DB {{ mysql_database }}'
  mysql_db: name={{ mysql_database }} encoding=utf8 collation=utf8_bin

- name: 'MySQL user {{ mysql_username }}'
  mysql_user: name={{ mysql_username }} password={{ mysql_password }} priv=*.*:ALL state=present

