---
- name: 'Develop tool profiles'
  template: src={{ item }} dest=/etc/profile.d/
  with_items:
    - java.sh
    - git.sh
    - editor.sh
    - ack.sh

- name: 'Developer tools'
  apt: name=vim,ack-grep,git,tree,jed

- name: 'Maven {{ maven_version }}'
  unarchive: >-
    src="https://www.apache.org/dist/maven/maven-3/{{ maven_version }}/binaries/apache-maven-{{ maven_version }}-bin.tar.gz"
    dest=/opt
    remote_src=Yes
    creates="/opt/apache-maven-{{ maven_version }}/bin/mvn"
