---
- name: 'Resize SD card'
  script: resize_sdcard.sh creates=/.mmcblk0_resized
  async: 0
  poll: 0
  ignore_errors: true
  register: reboot_required

- name: 'pause for reboot'
  sudo: no
  pause: seconds=30
  when: reboot_required|changed

- name: 'wait for reboot'
  sudo: no
  local_action: wait_for host="{{ inventory_hostname }}" search_regex=OpenSSH port=22 timeout=60
  when: reboot_required|changed

- name: 'Configure WIFI'
  copy: src=./wpa_supplicant.conf dest=/etc/wpa_supplicant/wpa_supplicant.conf mode=0600
  register: wpa_supplicant

- name: 'Update system packages cache everyday'
  action: apt update_cache=yes cache_valid_time=86400

- name: 'Reboot'
  command: /sbin/reboot -t now
  when: wpa_supplicant|changed

- name: 'SSH public key'
  authorized_key: user=pi key=https://github.com/chaifeng.keys

- name: 'zh_CN Locale'
  locale_gen: name=zh_CN.UTF-8

- name: 'en_US Locale'
  locale_gen: name=en_US.UTF-8

- name: 'Hostname'
  hostname: name={{ hostname }}.local

- name: 'Hosts file'
  lineinfile: dest=/etc/hosts regexp='^127\.0\.1\.1\t.+' line='127.0.1.1\t{{ hostname }}.local {{ hostname }}'
