---
- name: 'SSH public key'
  authorized_key: user={{ item }} key="ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDtKJbO7d17s72xTSLl6jL11aFvQWyCbwjQ5pZ1LmGRCHcS7iKM3YOV6e+U4eWQICSEkCFelrlxcMywOBRf9LycUoTBZDcrQyg3r91ekc1F4NeUy0KZre021OG89y8byNVPJUKKCCoOSR04A8yjhDlgGXb31QA22vZwr5Bet6D9Sx/LczDZ4IYe0ow2NAsCTHOxukHKBY+PDXVrdwN1wdop+FbmbMYjB/jbmjC2zwpD0JWHn7HidAmexOSrG1N2OWcfjWJbnVVt5y2uWjZTJxFR82Zjz4ZKZlZcEus6HSpxc2qbhhNrwAaP2TpksIqssfRUF6IVFz+xwzJQWiKNBCKN8P/4vHP1OLEc+dvnAwaF2EKkcxs1i6Yt+TrDGKVNqbn7TsKPWedCXveK+S0kAR48pLwmX5kN95of8SMoegjAcp4QP0GKZz6DVvlzUg5uObAQ8l9C5On6LRPQ2Bi6jLMpJDoX5l6jPQHmpFOURts29+s2ZaZcXvmxpXbANaFj8L38IZCv3/46rUcWtBWH1/uXArHTOBwNnA79ZRWljwZA3XnG+vEseU9yytkV+/ggfPn9/NilPZWBOxsbcWLaiQxf3mLinMG0MmOBRWqSH2FYqIHqM1fJutAH5MnWkB/8/IwC4X0mKtAhjTHyp2HVjOT1aVOil2OwjU9paWh0UFhq+Q== chaifeng"
  with_items:
    - pi
    - root

- name: 'Hostname'
  hostname: name={{ hostname }}.local

- name: 'Hosts file'
  lineinfile: dest=/etc/hosts regexp='^127\.0\.1\.1\t.+' line='127.0.1.1\t{{ hostname }}.local {{ hostname }}'

- name: 'VNC server/client'
  apt: name=tightvncserver,novnc

- name: 'apache default site configuration'
  template: src=apache2/default dest=/etc/apache2/sites-available/default
  notify: Restart apache2

- name: 'enable apache default site'
  file: path=/etc/apache2/sites-enabled/000-default
        state=link src=../sites-available/default

- name: 'vnc web client service'
  template: src=vncwebclient dest=/etc/init.d mode=a+x

- name: 'enable vnc web client service'
  service: name=vncwebclient enabled=yes

- name: 'use vnc display by default'
  template: src=vnc_display.sh dest=/etc/profile.d/
