---
- name: 'ensure RVM'
  shell: su -lc 'gpg --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3 && curl -sSL https://get.rvm.io | bash -s stable' {{ user }}
  args:
    creates: "{{ user_home }}/.rvm/scripts/rvm"
